"""
Shared constants for the TaoHash proxy.
"""

RELOAD_API_PORT = 5001
RELOAD_API_HOST = "0.0.0.0"

INTERNAL_PROXY_PORT = 3331
INTERNAL_DASHBOARD_PORT = 5000

DEFAULT_PROXY_PORT = 3331
DEFAULT_DASHBOARD_PORT = 5000

CONFIG_PATH = "config/config.toml"
